//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMCO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int Login_id { get; set; }
        public int PeopleID_FK { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool Login_Active { get; set; }
        public Nullable<bool> Login_Visible { get; set; }
        public Nullable<int> CreatedUserID { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> UpdatedUserID { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
    }
}
