//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMCO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Module_PermissionLevel
    {
        public int PermLevId_PK { get; set; }
        public string PermissionName { get; set; }
        public string PermissionDesc { get; set; }
        public Nullable<bool> InActive { get; set; }
        public Nullable<int> CreatedUserID { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> UpdatedUserID { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
    }
}
