//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMCO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_People
    {
        public int PeopleID_PK { get; set; }
        public string People_FN { get; set; }
        public string People_LN { get; set; }
        public Nullable<bool> People_Active { get; set; }
        public Nullable<bool> People_Visible { get; set; }
        public Nullable<int> CreatedUserID { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public Nullable<int> UpdatedUserID { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
    }
}
