//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMCO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_People_Module_X
    {
        public int People_Module_X_ID_PK { get; set; }
        public int PeopleID_FK { get; set; }
        public int Module_ID_FK { get; set; }
    }
}
